# Generated by Django 3.2.5 on 2021-07-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorymodel',
            table='categories',
        ),
    ]
